### ISSUE TITLE
[FEATURE] Add a swipe from the right side to show related commits to diff

### ISSUE THREAD

**Issue by wtfzdotnet** [sheimi/SGit#10]
When viewing a file it would be nice if there was the option for a right to left swipe, opening an overview of related commits to the file and creating the ability to diff between.

**Comment by phcoder** [comment]
Added one to my fork (Forker) at https://github.com/phcoder/SGit and https://play.google.com/store/apps/details?id=ch.phcoder.jigit

**Comment by maks** [comment]
Implemented in af041326ce8ee25dbacc567aaddc679289552895
