### ISSUE TITLE
New File Overwriting

### ISSUE THREAD

**Issue by Foggalong** [sheimi/SGit#102]
Creating a new file within SGit overwrites any exisiting file in the repo with the same name without prompting. To reproduce:

  1. Using SGit clone repo that doesn't contain a file called "test.txt"
  2. Using an external editor create a file called "text.txt"
  3. Save "test.txt" to the repos location on the device
  4. Using SGit create a new file in the repo called "test.txt"
  5. The file and all it's contents will now be overwritten with a blank file

SGit should at least notify the user that the file already exists. I've lost an hour of work through this so I hope a fix can be found :(

**Comment by maks** [comment]
I can't replicate this as of SGit v1.3.2 running on Nexus 5x with 6.0.1.
When I create a new file in another app in a repo working dir and then switch back to SGit, the newly created file *is* displayed in the file list and if you use SGit's "New File" menu item, a Toast is displayed saying "File already exists".
Please reopen if you are able to reproduce this with current version of SGit.
