### ISSUE TITLE
mention name of filesystem object in case of filesystem errors

### ISSUE THREAD

**Issue by als-git** [sheimi/SGit#107]
When SGit encounters a filesystem error (such as ENOTDIR during clone checkout because the
file TRAVEL was created and it looks for the directory travel (both of which exist in the repo))
it should explicitly mention the name of the problematic filesystem object, such as 
"error: TRAVEL: ENOTDIR" or equivalent to make troubleshooting for the user simpler.

See for an example: https://github.com/sheimi/SGit/issues/106

**Comment by maks** [comment]
This issue was moved to maks/MGit#61
