### ISSUE TITLE
Allow remote selection on pull and push

### ISSUE THREAD

**Issue by ajs124** [sheimi/SGit#108]
I use multiple remotes and would like to be able to choose between them for pulling and pushing.

Currently I'm unable to find such an option and since there is also nothing to edit remotes (should I file another bug/feature request for that?) I have to open the git config manually with a text editor and change stuff around.

**Comment by scholi** [comment]
Agree. I found remote choice in pushes but not in pulls. This would be very useful

**Comment by phcoder** [comment]
I implemented missing part in my fork: https://play.google.com/store/apps/details?id=ch.phcoder.jigit source https://github.com/phcoder/SGit

**Comment by maks** [comment]
Implemented in af041326ce8ee25dbacc567aaddc679289552895
