### ISSUE TITLE
Code highlight syntax for java file.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#117]
I have 2 repositories. One is for C project and other is java project. 
However, SGit editor can only do the highlight syntax for C file but not java file.

**Comment by d10** [comment]
This seems to work for me. Could you give some details about the file that doesn't highlight? Ie. File name and file size.

**Comment by d10** [comment]
We will be removing the editor in the next version of SGit, as the current editor (and others) have varied bugs which prevent proper editing of files. For now, you should use a specialized code editing app.
