### ISSUE TITLE
Better warning for conflict.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#118]
Step to reproduce.
- Go to the project repository.
- Click on a file to open it.
- Choose the edit icon on the right corner
- Type in some abitrary text
- Click on the menu icon again.
- Choose commit.
- Type in the commit message
- Go to the repository URL in web browser
- Login.
- Click on the same file that has just been edit in local repository
- Type in some abitrary text, different from the text typed in earlier.
- Commit it on the remote repository
- Push the commit on local device.

Outputs:
- SGit should inform users about the conflict. However, the message SGit show is "Remote ref update was rejected". I think it is quite confusing for users, a warning about the conflict and suggestion that users should pull from the remote first will be more informative and useful for users especially for someone is new Git.

**Comment by maks** [comment]
This issue was moved to maks/MGit#60
