### ISSUE TITLE
Delete file along with the folder.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#120]
Steps to reproduce:
- Create a new folder.
- Create a new file named File1 inside the folder.
- Long press on the file to bring up the dialog.
- Choose Add to stage option.
- Delete File1.

Outputs:
-File1 is deleted as expected. However, the folder is also deleted without any confirmation or notification to users.
- In case only want to delete that file but the folder contains that file also gets deleted.

**Comment by d10** [comment]
Closed by #140.
