### ISSUE TITLE
Inform users about the Internet connection.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#122]
Steps to reproduce.
- Turn off internet connection
- Click the + icon in the right corner of main screen
- Fill in the needed information such as Repository URL/local path/ user name/ password

Output:
- SGit does not inform about the Internet connection.

It should be nicer if SGit inform the users about the Internet connection before letting users do any internet related activities.

**Comment by maks** [comment]
This issue was moved to maks/MGit#57
