### ISSUE TITLE
Git reset delete the files.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#123]
Steps to reproduce.
- Create a folder with two files named File1 and File2
- Add them to stage
- Click the menu icon on the right corner.
- Choose Reset

Output:
-The application delete two files and the parent folder

In fact reset just delete the commit and not the files itself, it must leave the repository untouched. However, SGit delete the commit and also the files.

**Comment by bclermont** [comment]
I suffer from that bug as well combined with https://github.com/zeapo/Android-Password-Store/issues/236 that caused files to be deleted.

**Comment by maks** [comment]
This issue was moved to maks/MGit#56
