### ISSUE TITLE
Show plain text password when users choose to remember password and username

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#124]
Steps to reproduce:
* This action must be done on a rooted phone.
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- Tick the Remeber password box
- Click OK to start cloning a repository
- Connect the device to a laptop
- Open the DDMS in Android Studio
- Choose File Explorer tab in the DDMS
- Navigate to folder data/data/me.sheime.sgit/databases
- Click to choose the repo.db file
- Export file to desktop
- Open the file using SQLite Browser

Output:
- The password is stored in plain text

- Users password should be stored encrypted.

**Comment by phcoder** [comment]
This won't give you anything. They password must remain decryptable by sgit as you need it in plain text form to access the repo. So anyone who is able to pull the database in the first place (you need root for this) will be able to replace SGit with a version that decrypts the passwords and show them in plain text. It's only useful to encrypt if you set a master password.
