### ISSUE TITLE
Switching between different Internet connection type.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#125]
Steps to reproduce:
- Turn on 3G connection and turn of wifi
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- In the middle of the download progress, change the network connection from 3g to wifi.

Outputs:
- The repo got deleted but there is no prompt to download again. SGit showed the wrong notice. (“Connection timeout”).
![timeout](https://cloud.githubusercontent.com/assets/10162972/5592351/9830878a-91fd-11e4-92cd-20b66a275809.png)

**Comment by d10** [comment]
I think this behaviour is reasonable, as there's nothing we can do to pause the download.
