### ISSUE TITLE
Interruption while download a new repo

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#126]
Steps to reproduce:
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- Make a phone call to the phone that the download is in progress

Output:
- Download is hung or the repository is deleted.

Sgit should allow users to receive the phone call and ontinue to download after the call stops.

**Comment by maks** [comment]
I cannot replicate this with current version of SGit running on Nexus 5x on 6.0.1
