### ISSUE TITLE
Download a new repo when the previous repo is hung, discard the previous repo make the application crash.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#127]
Steps to reproduce:
- Download the first repository
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- Rotate the device
- The first downloading repository is hung.
- Download the second repository
- Click the + icon in the right corner again
- Fill in the needed information such as Repository URL/local path/ user name/ password
- Discard the previous hung repository

Output:
- The application crashes

**Comment by maks** [comment]
This issue was moved to maks/MGit#59
