### ISSUE TITLE
Download hung when rotate the device.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#128]
Steps to reproduce:
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- Rotate the device

Output:
Download is hung

**Comment by liscju** [comment]
I can't reproduce behaviour on Kiano Fly 9.7 Quad tablet with 4.1.1 Android.

**Comment by maks** [comment]
I cannot replicate this either with current version of SGit.
