### ISSUE TITLE
SGit can only work with one account at a time

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#129]
Steps to reproduce:
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- Click the + icon in the right corner again
- Fill in the needed information such as Repository URL/local path/ user name/ password which is different from the previous clone

For example, the input is like this
- Repository URL: https://github.com/path/repo_name
- Local path: SUT
- Username: myusername
- Password : mypassword

- Repository URL: https://github.com/path/AnotherProject
- Local path: AP
- Username: anotherusername
- Password : anotherpassword

SGit can only save the information of one account and allow to work with one repository at the time.
 The application can only work with one account. In case that users have 2 or more accounts, and they are working on different projects at the same time, the application does not work.

**Comment by d10** [comment]
I don’t plan to add support for multiple accounts in the new future. However, if anyone sends a PR, I’m willing to accept it.
