### ISSUE TITLE
Custom storage location of downloaded repositories

### ISSUE THREAD

**Issue by Tungul** [sheimi/SGit#13]
Basically, a setting that allows you to specify where you want the repos to go when they are downloaded, as opposed to just dumping them into /sdcard/Android/data/me.sheimi.sgit

Defaulting to there is fine, however.

Additionally, have an option when changing the download location to move the repos from their previous location to the new one, so they aren't lost somewhere, and so you don't have to redownload them.

**Comment by meeb** [comment]
Just adding my +1 for this as it would be a most useful feature.

**Comment by willsheppard** [comment]
+1 this effectively prevents me from developing on my phone directly in a checkout directory, because other IDE apps also have fixed directories.

**Comment by ecommunities** [comment]
+1 I'm working with a very large repo and need to be able to put it somewhere (ext sdcard) that won't impact my ability to use my  phone ;)  Love this app though, thanks!
