### ISSUE TITLE
While downloading a new repo cannot do anything else with other repo

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#130]
Steps to reproduce:
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- While waiting for the download to complete change to another existed repo to work on, such as push, pull, check the status, check the commit message .

Output:
SGit can only work on the download, cannot work on any other repo.
It should be better to allow users to multitask

**Comment by liscju** [comment]
I can't reproduce behaviour on Kiano Fly 9.7 Quad tablet with 4.1.1 Android. ,can u supply information about your mobile device and android version?

**Comment by maks** [comment]
I can't reproduce this either with current version of SGit.
