### ISSUE TITLE
Directly delete a repository from Android/data/me.scheimi/files/repo but that repository still shows in the user interface of SGit

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#131]
Steps to reproduce:
- Go to Android/data/me.scheimi.sgit/files/repo.
- Remove a repository.
- Go back to SGit

Output:
- SGit cannot detect that the repo has been deleted and still show the repo in the user interface. 
- When choose that repo, the toast message shows that 
  "Repositoy not found (there may be something wrong with this repo).

**Comment by maks** [comment]
This issue was moved to maks/MGit#55
