### ISSUE TITLE
The application is in the wrong state, when a folder is already deleted still remains in mobile storage.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#132]
Steps to reproduce:
- Click the + icon in the right corner
- Fill in the needed information such as Repository URL/local path/ user name/ password
- Make the app hung by rotating device
- Check the repo presented in the interface of SGit should be the same with the data presented in the phone data.

Output:
- Becaue the download is error, the repo only gets deleted in the SGit 
- The repo is not deleted in the mobile data and it is the incompleted downloaded
  repo.

Here is the screenshots show the repo in SGit and the repo in android/data
![screenshot_2014-12-29-12-58-18](https://cloud.githubusercontent.com/assets/10162972/5592549/b7a55d9e-9206-11e4-8573-0d5b70bccf2d.png)
![screenshot_2014-12-29-12-58-34](https://cloud.githubusercontent.com/assets/10162972/5592550/bb88efca-9206-11e4-893b-06b0e39994e0.png)
![screenshot_2014-12-29-12-58-55](https://cloud.githubusercontent.com/assets/10162972/5592552/c1f28844-9206-11e4-99cb-2ab2c969a38b.png)

**Comment by maks** [comment]
Sorry I can't reproduce this, rotating the device while cloning does not hang the app either before or during cloning.

**Comment by maks** [comment]
This issue was moved to maks/MGit#58
