### ISSUE TITLE
Files are created in both branches before push

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#133]
Steps to reproduce
- Go to the directory that has more than one branch.
- Choose one branch to work with.
- Add new file to that branch only, add to stage, commit.

Output:
- The file is created in every branches.

I think it would be less confusing for users if the file is created in one branch then it can only be seen in that branch and not other even before users push to remote.

**Comment by d10** [comment]
I don't get what you mean by branches. Could you clarify?

**Comment by d10** [comment]
Closing due to staleness.
