### ISSUE TITLE
Add fetch functionality

### ISSUE THREAD

**Issue by jackyyf** [sheimi/SGit#137]
Requesting fetch functionality, so that I can just fetch from remote origin, instead of merge into current branch.

**Comment by d10** [comment]
Agreed. This will probably take some time.

**Comment by maks** [comment]
Actually this could be fairly straight forward as jgit already has a top-level API FetchCommand: https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit.test/tst/org/eclipse/jgit/api/FetchCommandTest.java

so we need a new FetchTask in repo.tasks that works along the lines of the existing PullTask.

**Comment by bigdavedev** [comment]
@maks: I have a commit that fetches from the tracking remote (origin).  I am trying to implement a dialog that will allow you to choose from multiple remotes, should you have that configured. I believe that would suffice for the majority of SGit's users.  Fetching from specific refspecs would be best left as a feature request later on.  

To summarize, I intend to deliver the following:
- [x] Fetch from origin (default)
- [ ] Fetch from selected remote
- [ ] Fetch all remotes

**Comment by maks** [comment]
@bigdavedev sounds great!
Agreed, pulling specific respect IU s pretty specialized functionality.
 Please send through PR, happy  to talk it over even while it's in progress if you like.

**Comment by maks** [comment]
Implemented in ee97161c36de62ff5277de444fdbad0ae31d008c
