### ISSUE TITLE
can't init local in /sdcard/shadertoy/ 

### ISSUE THREAD

**Issue by znsoft** [sheimi/SGit#138]
try enter local path /sdcard/ShaderToy  for init local repo in any path and got error: Repo name cant contain slash . how to create/init    local/offline  repo in any folder, not in /sdcard/.android/....../repo/local ?

**Comment by d10** [comment]
Currently, this can't be done. We will work on adding support for that. For now you can create a repo, then copy it to the location you prefer it to be on, and import the repo as an external one.

**Comment by znsoft** [comment]
thanx for explain i'll try it way
