### ISSUE TITLE
ART lollypop support

### ISSUE THREAD

**Issue by hafkensite** [sheimi/SGit#142]
App forceclosed when I clicked on a repo, and am unable to add a new one after reinstall.

On my raspi ssh server I get this in my auth.log:

    Feb 26 14:05:25 raspi sshd[19106]: Received disconnect from 123.45.67.8: com.jcraft.jsch.JSchException: Auth fail [preauth]

**Comment by d10** [comment]
Can you provide more details? Did you just clone a repo? Do you use SSH keys?

**Comment by d10** [comment]
Ping?

**Comment by hafkensite** [comment]
Sorry,must have missed your first reply.
I want to clone a repo, over ssh using keys.
What is strange is that the server seems to log a Java exception.
Is it difficult to see the entire stack trace?

Ping?

—
Reply to this email directly or view it on GitHub
<https://github.com/sheimi/SGit/issues/142#issuecomment-81349840>.

**Comment by phcoder** [comment]
Could you try https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit. I updated jsch there

**Comment by maks** [comment]
@hafkensite please reopen if this is still an issue for you.
