### ISSUE TITLE
Support rebase command

### ISSUE THREAD

**Issue by mdumrauf** [sheimi/SGit#144]

**Comment by d10** [comment]
Rebase is supported, unless you're referring to interactive rebase?

**Comment by mdumrauf** [comment]
Correct. I meant interactive rebase.

**Comment by d10** [comment]
I think that it would be to difficult to do so, so I'm closing this issue. I would accept PRs though.

**Comment by mdumrauf** [comment]
Maybe providing an optional CLI?

**Comment by d10** [comment]
Not too sure what you mean by CLI, especially on mobile. Anyway, I'll see how it goes, but it's not high on my priority list unless someone send a PR.

**Comment by mdumrauf** [comment]
Command Line Interface. It would be like offering Git in the natural way.

**Comment by d10** [comment]
Ah, that's true. But it would be difficult to implement for example all the edit prompts for amending commits etc. I'll definitely look into it in the future when one cleared down on the remaining issues and bugs. Interactive rebase on mobile would be so cool! ;)

**Comment by mdumrauf** [comment]
Would bash + vim be enough? I've been waiting for it for a long time. I guess I will do it myself.

**Comment by d10** [comment]
I'm not too sure what you mean. Compile and include bash/vim in Android? I think that would be too far of a stretch. Currently we just use JGit, a Java implementation of Git, for all our commands.

**Comment by mdumrauf** [comment]
I'll try to take a look in the short term. But yes, that's what I meant.
