### ISSUE TITLE
Crashes whenever a repo is cloned

### ISSUE THREAD

**Issue by pitaj** [sheimi/SGit#145]
I'm trying to come my own repo of Github. I provide the repo URL (https), the local path, username, and password. Whenever it gets to `Updating references`, it crashes. When I open the so again, it shows `Updating references` for forever on the repo.

**Comment by pitaj** [comment]
It even crashes without any username or password entered.

**Comment by d10** [comment]
Are you using Android 4.4 with ART?

**Comment by pitaj** [comment]
I'm on 4.4.4 with ART enabled.

**Comment by d10** [comment]
This is an issue with ART on pre-Lollipop devices. See #103. There's nothing we can do about this for now.
