### ISSUE TITLE
Cannot use ssh on a non standard port

### ISSUE THREAD

**Issue by nikkilocke** [sheimi/SGit#146]
As I understand it, git should accept a url of the form ssh:/user@host:port/path/to/repo, but SGit doesn't.

**Comment by d10** [comment]
They are supported: see https://github.com/sheimi/SGit#ssh-urls. Your URL is missing a `/`, it should be `ssh://`

**Comment by nikkilocke** [comment]
Thanks, so I realised, which is why I closed the bug immediately. Sorry for wasting your time.

I am impressed with SGit - the only difficulty I am having now is figuring out how to copy and paste in the editor.

Regards,
Nikki

On 15 March 2015 11:39:30 GMT+00:00, Benjamin Tan <notifications@github.com> wrote:
>They are supported: see https://github.com/sheimi/SGit#ssh-urls. Your
>URL is missing a `/`, it should be `ssh://`
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sheimi/SGit/issues/146#issuecomment-80978720

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by d10** [comment]
Just a heads up: we're removing the editor in the next version of SGit, as it has many issues. You can also check out other apps like DroidEdit and Quoda.
