### ISSUE TITLE
Duplicate commit messages on Commits tab

### ISSUE THREAD

**Issue by porkness** [sheimi/SGit#148]
All the commit messages are displayed twice
like the following
```
       Commits
----------------------
yyyyyyyyyy
Commit 2
AUTHOR DATE
----------------------
xxxxxxxxxx
Initial commit
AUTHOR DATE
----------------------
yyyyyyyyyy
Commit 2
AUTHOR DATE
----------------------
xxxxxxxxxx
Initial commit
AUTHOR DATE
----------------------
```
One strange thing is if you do pull or reset, the duplicated message temporarily disappears, but they will re-appear if you go back to the repo list and re-enter the repo.

**Comment by d10** [comment]
This issue has been fixed by #69.
