### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by uroybd** [sheimi/SGit#149]
First of all, it is an awesome app. I would like to even donate if I can. (But I'm unemployed.)

I request a search feature becasue it would help us to find code snippet or file faster.

I believe file search is not a hard task for you to implement and the ‘in file search’ is also possible. I found a opensource app named agrep in google play. If you please add these features, I will be greatfull.

Thanks.

**Comment by d10** [comment]
Not too sure about that. The plan currently is to just build an app with a minimum amount of Git-only features. Currently we still have many features left, many issues and I’m not very free currently. If you create a PR for this I'll consider it. Otherwise I'm closing this for now.
