### ISSUE TITLE
Include darker theme option

### ISSUE THREAD

**Issue by Tungul** [sheimi/SGit#15]
Honestly, the blue theme is really pretty and all, but sometimes I don't like having my eyes scorched.

A darker or black theme would be nice.

**Comment by KOLANICH** [comment]
I'd say that black theme (w/o bright regions) is also required

**Comment by d10** [comment]
This isn't the most important feature for now, so I won't be actively working on it. I'll definitely accept PRs for it though.

**Comment by phcoder** [comment]
Added one to my fork (Forker) at https://github.com/phcoder/SGit and https://play.google.com/store/apps/details?id=ch.phcoder.jigit

**Comment by maks** [comment]
Implemented in af041326ce8ee25dbacc567aaddc679289552895
