### ISSUE TITLE
Cloning remote repository not working

### ISSUE THREAD

**Issue by shaun27stars** [sheimi/SGit#151]
Cloning a repository, it reaches the end - "updating references: 100%" and then the repository disappears again.

The following message appears briefly:
attempt to use inflator after calling end

Repository is on BitBucket, https.
Device: Android Galaxy Tab 10.1
Android version: 4.0.4

SGit version 1.2.4.4

**Comment by Nikitaw99** [comment]
Was the repo large or not? Just to be sure.

**Comment by maks** [comment]
This issue was moved to maks/MGit#51
