### ISSUE TITLE
config edit

### ISSUE THREAD

**Issue by rigid** [sheimi/SGit#154]
A UI way to do "git config --edit" would be nice.

**Comment by d10** [comment]
I think that is too specific and niche for SGit to support. I’d gladly accept pull requests for this, but won’t implement it myself.

**Comment by rigid** [comment]
ok. i thought some small "open .git/config" as text/plain, so that the user may choose the favourite text editor, would be convenient as long as things like self signed certificates/"certificate pinning" aren't implemented.
