### ISSUE TITLE
Update from upstream

### ISSUE THREAD

**Issue by DJaeger** [sheimi/SGit#156]
I cant get update from upstream repo to work.
It seems I do nothing withing with the remote repo.
I can't choise it for merge, nor for pull or rebase.
Only for push, where I get an "git-receive-pack not permitted" error
How can I do it with SGit?
Is is not possible, am I doing it the wrong way or is it simply damaged?

**Comment by maks** [comment]
Is this still an issue for you? If so could you please provide more information such as url of the repo and what you are trying to do?

**Comment by DJaeger** [comment]
Yes, it still exists.
I have added a fork to SGit:
https://github.com/DJaeger/Android-IMSI-Catcher-Detector
Then I added the upstream repo as remote repo:
https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector

But I can not change to it or choose it anywhere to pull or  merge from it.

**Comment by maks** [comment]
Great, thank you for including the repo urls. I'll test this as soon a I get a chance.

**Comment by DJaeger** [comment]
You can also use every other fork for testing

**Comment by maks** [comment]
Should be fixed as of af041326ce8ee25dbacc567aaddc679289552895
