### ISSUE TITLE
symlink behavior strange

### ISSUE THREAD

**Issue by wxl** [sheimi/SGit#159]
So my repo has some symlinks. Normally, on desktop, I have no problem with these. However, when pulled in by SGit, they are converted to text files containing the location they point to. Worse, when a push is made, regardless of whether or not these files are touched, they overwrite the symlinks.

**Comment by d10** [comment]
Hmm, I'm not very experienced with symlinks. Would appreciate any help here.

**Comment by wxl** [comment]
according to [this answer on StackOverflow][1], the default behavior for
recent versions of git is to store symlinks as SGit does. it's the push
that's funky, as it stores the file as a standard text file rather than
turning it back to a symbolic link.

[1]:
http://stackoverflow.com/questions/954560/what-does-git-do-to-files-that-are-a-symbolic-link

**Comment by maks** [comment]
A number of points need to be made here.
First of, at least on Linux, symlinks are infact exactly that, a text file whose contents are the path the symlink points to, its just that there is extra metadata to tell the filesystem that it is a symlink and not regular file, see: http://man7.org/linux/man-pages/man7/symlink.7.html (third paragraph)

Now what makes this issue more problematic is that not all fileystems (eg. FAT) support symlinks irrespective of in you are using a LInux kernel or not. On an android device you could quite likely be using a FAT filesystem on the storage device you use for your git repo working directory.
But things get worse in that up to Java 7, java didn't support creating symlinks, support was added via NIO (http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createSymbolicLink(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...)
and in Android it was only added in 21:
https://developer.android.com/reference/android/system/Os.html#symlink(java.lang.String, java.lang.String)
though there is a hack that could allow support on older versions: http://stackoverflow.com/a/27726687/85472

And finally jgit, the library the SGit uses for its git implementation only gainded support for symlinks around Feb 2014: https://bugs.eclipse.org/bugs/show_bug.cgi?id=354367 and while I haven't had a chnace to have a detailed look at the commit that added support, it looks like it dynamically loads in support using Java 7s API not Androids. 

So its doable but there are alot of moving parts including I suspect contributing a patch back upstream to jgit to add support for Symlinks on Android.

Of course PRs are welcome but I don't think I'll have a chance to work on this in the near future.

**Comment by maks** [comment]
This issue was moved to maks/MGit#52
