### ISSUE TITLE
Repo force update is required

### ISSUE THREAD

**Issue by KOLANICH** [sheimi/SGit#163]
Thr app doesn't allow to push commits rewriting already existing commits. We need ```--force``` analogue

**Comment by phcoder** [comment]
This is implemented in dev branch and was uplifted to my fork: https://github.com/phcoder/SGit

**Comment by KOLANICH** [comment]
Thanks. Could you
1 create issues sections in your repo
2 put your app into f-droid

**Comment by phcoder** [comment]
I created issues section. I quickly read how to submit to F-Droid. It's not entirely clear to me yet. I'll see later how to publish on F-Droid

**Comment by phcoder** [comment]
@KOLANICH : unfortunately I can't contribute anything to fdroid repo due to it being AGPL. However I do create tags ver_<code revision> for every play store release. Feel free to submit app to fdroid enabling it to track tags

**Comment by KOLANICH** [comment]
I have no ideawhy can't you, in fact the original sgit is [already in fdroid](https://f-droid.org/app/me.sheimi.sgit). Also I don't uderstand why you have mentioned agpl, how is it connected to this case?

**Comment by phcoder** [comment]
In order to add Forker to FDroid, I'd need to write a manifest for it and put it into FDroid repo. FDroid repo is under AGPL and I can't contribute to any AGPL repo. However as I said I'd be perfectly fine if somebody else contributed missing metadata to FDroid

**Comment by maks** [comment]
Fixed in 29c740dd351e2440e507fb515f1d7214d9cb48ad and included as of build 1.3.0 on Google Play.
