### ISSUE TITLE
Support more ssh ciphers

### ISSUE THREAD

**Issue by kaueraal** [sheimi/SGit#165]
Currently SGit does support only few ssh ciphers. Several important ones such as aes256-ctr, aes256gcm or chacha20-poly1305 are missing.

**Comment by kaueraal** [comment]
The same issue arrises with the key exchange method. curve25519-sha256@libssh.org and diffie-hellman-group-exchange-sha256 are missing.

**Comment by phcoder** [comment]
Should be fixed in https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit. Note: I made a fork only because my pull requests went unanswered. I'm welcoming any merge back into SGit. I updated jsch to newest version there.

**Comment by maks** [comment]
Implemented in af041326ce8ee25dbacc567aaddc679289552895
