### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by peter-vanpoucke** [sheimi/SGit#166]
Hi

I've just installed sgit, but when I open it, it just crashes.  I'm on Android 6.0 (MRA58K).  I can't seem to report the crash from my phone.  I already reinstalled.

Let me know if I can test some things...

Kind regards

Peter Vanpoucke

**Comment by d10** [comment]
Not too sure about this issue as I don't have an Android 6.0 device. If you have any ideas how to fix it, feel free to send a PR.

**Comment by Lrs121** [comment]
Here's a logcat. I dont know if this will help.

http://lrsservers.ddns.net/download/Sgit_M_crash_trunc.txt

Device: Nexus 6
OS ver: Android 6.0
Security Patch: October

**Comment by MrSchism** [comment]
@d10 are you taking over for @sheimi?

**Comment by d10** [comment]
Yeah, I've been making some patches and fixes, but recently I've also been quite busy, so I'd really appreciate for others to contribute.

**Comment by MrSchism** [comment]
Alright. I wasn't certain on if you had a second repo out or if you were a maintainer here.

**Comment by Flamma** [comment]
Same problem.

sgit crashes at start in my android 6.0.

No idea on how to fix it.

**Comment by Lrs121** [comment]
I got it working. I've done some testing and the app seems functional, though I may have disabled something that didn't need to be disabled. I wanna get some more testing of it done before submitting a pull request, however I have a debug release made if people would like to test it. There is some important information in the tag so please read if you would like to try it out.

https://github.com/Lrs121/sgit/releases/tag/m-bringup

-Lrs

**Comment by Flamma** [comment]
Works for me. At least, I've been able to open the application (weee!), to clone a repo, and to commit and push changes.

**Comment by scofflan** [comment]
Works for me also. Everything seems to work correctly so far. Thanks

**Comment by phcoder** [comment]
Should be fixed in https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit. Note: I made a fork only because my pull requests went unanswered. I'm welcoming any merge back into SGit.

**Comment by maks** [comment]
Fixed in 2aea840de55d62bb469eb84fd2342129a2a1e30d
