### ISSUE TITLE
"invalid privatekey" error when interfacing with gitosis

### ISSUE THREAD

**Issue by copiesofcopies** [sheimi/SGit#17]
This is probably an error in my configuration of Gitosis, but the error message rendered by SGit makes it very difficult to track down. I'm trying to connect to a repository hosted via gitosis. I've imported a private key into SGit and committed the corresponding public key to Gitosis, but when I attempt to connect, SGit gives me an "invalid privatekey" error. (It also wipes out all of the information I entered about the repository, requiring me to painstakingly type it all back in to try again.)

Can you tell me whether this error means that the host rejected the private key, or whether SGit has determined the key is invalid? Thanks.

**Comment by phcoder** [comment]
This is not SGit problem but jsch. Older jsch that is used on most android devices accepts only headers like:
-----BEGIN DSA PRIVATE KEY-----
or
-----BEGIN RSA PRIVATE KEY-----
whereas some tools including vx connectbot generate a key with header
-----BEGIN PRIVATE KEY-----
i.e. without indication whether it's RSA or DSA. As a workaround you can modify the header in text editor but you need to know whether it's RSA or DSA key.
As another possiblity you can generate the key in SGit itself if you use my patch for this

**Comment by phcoder** [comment]
Should be fixed in https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit. Note: I made a fork only because my pull requests went unanswered. I'm welcoming any merge back into SGit.

**Comment by neitsab** [comment]
This should be fixed by 151d89558e but couldn't test it

**Comment by maks** [comment]
Yes and also I have upcoming changes cherry-picked from phcoder's fork that will allow generating key pairs from within SGit also.
I'm going to close this for now - if anyone is able to replicate the issue, please feel free to reopen this issue.
