### ISSUE TITLE
Maintainence

### ISSUE THREAD

**Issue by demoneaux** [sheimi/SGit#170]
/cc @sheimi @phcoder

I used to maintain this repository more actively, after obtaining permission from @sheimi. However, of late, I haven't been able to find the time to contribute. I've seen @phcoder try to do so by forking the repository and adding features. If possible, @sheimi could you add him as a maintainer as well?

@phcoder perhaps you could rebase your commits to add them here when you're a maintainer.

**Comment by phcoder** [comment]
Privileges to commit to github repo aren't going to be enough. What SGit desperately needs are releases to Play Store

**Comment by d10** [comment]
Yeah, I was going to do a release around May, but many things came up. Hopefully @sheimi can spare some time to release every now and then, or help to work things out in order to provide a way for you to release to the Play Store. Thanks very much for your contributions @phcoder! Let's wait for @sheimi to respond :)

**Comment by maks** [comment]
@sheimi has been kind enough to allow me to take up maintenance of the project.
I'd like to get a new release out asap, so @phcoder if you have the time to rebase any outstanding PRs that you'd like included please let me know and thanks for all your contributions to the project.

**Comment by maks** [comment]
Actually having started looking through your repo @phcoder I can see you've done a lot of work on the codebase over the last year! Great stuff!
I spotted your comment in #166 that you'd still like to merge back into here, so if that's the case, I'd like to work out a plan for creating a series of PRs to merge all your work back in or as much as makes sense. Switching to a gradle build and getting 6.0 compatibility would be my priorities, though I'll have to see how much other things the 6.0 fix needs.

**Comment by demoneaux** [comment]
:+1:! Thanks @maks for contributing! I tried to do some work last year, but ended up slowing as I got busy. I think merging in @phcoder’s work and adding him as a contributor would be great as well!

**Comment by maks** [comment]
I'd be happy to have @phcoder added as a contributor too as he has certainly done a lot of work on the app in his fork, but having only write access to the repo as a contributor myself, it would need to be @sheimi call as the owner of this repo.

**Comment by maks** [comment]
I'm going to close this for now as I'm able at the moment to do active development as well as maintaince. I'd invite everyone on this issue to come discuss things over on https://gitter.im/sheimi/SGit or just keep contributing issues and PRs here.
