### ISSUE TITLE
Repo clone USERAUTH Fail 

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [sheimi/SGit#171]
I have a git repository hosted on centos with gitolite. I use JuiceSSH to connect and admin my server. I exported my JuiceSSH private key, imported it into SGit, and try to clone a repository but get the above error.

Normally I clone `Repo.git` with the following command

    git clone git@domain.tld:Repo

I have tried every combination I can think of for the remote URL including the example formats for this repo and I haven't been able to get my repo to clone. I have tried the following plus a dozen other combinations. I have tried with and without the username field filled.

>ssh://git@domain.tld/Repo.git
>ssh://git@domain.tld/Repo

>https://git@domain.tld/Repo.git
>https://git@domain.tld/Repo

>git@domain.tld:Repo

I tested the key I exported with the following command and it connects fine. 

    ssh -i test.key git@domain.tld

What would the proper format for the remote URL be based on my example clone? Is it possible there is some issue because of gitolite?

**Comment by phcoder** [comment]
juicessh keys require newer jsch. Could you try https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit ? I updated jsch there. It's also able to generate the key itself

**Comment by ZombieProtectionAgency** [comment]
@phcoder I tried JGit but it didn't work. I generated a new key on my server, running centos, and it seems to be working now so I think you were right either way...

**Comment by phcoder** [comment]
Did you try generating the key directly in JiGit out only importing JuiceSSH one?

**Comment by phcoder** [comment]
Is JuiceSSH key RSA or ECDSA? ECDSA is not supported in jsch AFAIR

**Comment by ZombieProtectionAgency** [comment]
The JuiceSSH key was RSA. I didn't try generating the key in JiGit.

**Comment by phcoder** [comment]
I tried it myself with JuiceSSH and Forker (I had to rename JiGit to avoid anti-spam problems). Can you provide me with a sample key? Meanwhile I updated jsch to 0.1.53. SGit has 0.1.50, JiGit had 0.1.51, in Forker it's 0.1.52, perhaps this helped

**Comment by ZombieProtectionAgency** [comment]
Sorry I didnt reply right away. I will try to test this today and let you know.

**Comment by maks** [comment]
@ZombieProtectionAgency  Please reopen if this is still occuring with the latest release (1.3.0) of SGit.
