### ISSUE TITLE
Problema ao puxar projeto

### ISSUE THREAD

**Issue by antoniodiego** [sheimi/SGit#175]
Estou tendo um problema ao puxar (Pull) o projeto para o celular.

**Comment by maks** [comment]
Sorry you will need to provide more information please.

**Comment by antoniodiego** [comment]
Tive um problema ao tentar puxar um projeto.

**Comment by maks** [comment]
Sorry, I meant you'd need to provide more information such as:
* URL of  the repo (if it's publicly available)
* what specific error you got (screenshot is good too)
* Which device, version of Android and version of SGit you were using
* etc

**Comment by antoniodiego** [comment]
This make a time.
The repository I belive what I have deleted.

**Comment by antoniodiego** [comment]
Aqui está o endereço do repositório : https://github.com/antoniodiego/pocessador-arquivo-base-midia-ISO

**Comment by maks** [comment]
This issue was moved to maks/MGit#71
