### ISSUE TITLE
Edit file does not save

### ISSUE THREAD

**Issue by VivianePons** [sheimi/SGit#185]
When I open an md file and click the edit button it opens another app called Writely but when I change something in the file through Writely, it doesn't save! It used to be that the edit button would just allow me to edit the file directly using sgit but it seems that it is not the case anymore.

**Comment by maks** [comment]
The new behaviour tries to use any existing app that you have installed that has registered for edit action intents for the file type you are opening. Previously all files would be opened within a basic html-based editor (using the codemirror editing component).
I would expect that the app you are using (Writely) should have either an explicit means of saving file edits or automatically save edits when you leave the app.
I'll try to test and replicate this to see if there is some issue with the way the integration between SGit and Writely happens.

**Comment by VivianePons** [comment]
Somehow, writely is saving them but not in the right place / file, I'm not sure what's happening there. The problem is to find an app that is easily compatible with sgit. I'm using JotterPad now for md files but it is probably not "registered" as you say: I cannot edit from within sgit, I have to open JotterPad and find the find the file explicitly in the android file system. 

What I liked about the old way is that I didn't need an extra app. I understand that you don't want to maintain a full editor but it was good to have a simple option on the spot. It was very confusing when I updated the app, basically, I could not use it anymore! It took me some time to find a workaround.

Anyway, thank you for your work and the attention to my problem.

**Comment by maks** [comment]
I  quite agree that there should be the choice to use SGit's built in
editor, especially given that in Android its quite likely that there will
not be suitable editors for many files types.
There needs to be a user preference to set if external or internal editor
should be used, I'll leave this issue open to track implementing that
feature.

----
Maksim Lin -- Freelance Android Developer
www.manichord.com

**Comment by pabloxeven** [comment]
@maks -> Is there any specific app you would recommend to edit **plain text files** (or common used files such as **.c**, **.cpp**) ?

_When not using an IDE, in my desktop I'd use Sublime or any other text editor._

What would you recommend to use on Android? I have been looking at some alternatives but I'd appreciate _your advise_.

**Tnks!**

**Comment by demoneaux** [comment]
@pabloxeven I'm currently using QuickEdit.

**Comment by maks** [comment]
I'm bringing back the internal text editor in the next release (1.3.3) which should help resolve this issue.

**Comment by maks** [comment]
Internal editor now available again as of af041326ce8ee25dbacc567aaddc679289552895
