### ISSUE TITLE
EINVAL error

### ISSUE THREAD

**Issue by LeftPinkie** [sheimi/SGit#188]
I get an 'EINVAL' error while trying to clone a repo. The app does the download and reconciliation, then it errors out. Any idea as to what this error means or how I can resolve it?

**Comment by maks** [comment]
If possible, could you please provide the url for the repo that is causing the error?
A screenshot with the error you are getting, along with which version of Android and version of SGit would also be very helpful.

**Comment by maks** [comment]
This issue was moved to maks/MGit#53
