### ISSUE TITLE
Commit UI non-intuitive

### ISSUE THREAD

**Issue by bigdavedev** [sheimi/SGit#194]
I feel that the commit list view behaves counter to the Android philosophy.  When I click a commit I expect to be shown the diff for the commit.  Likewise, when I long press on a commit, I expect to be given the ability to select one or more commits to diff between, or the option to cherry-pick/checkout the selected commit etc. (currently, the action performed on long press is checkout).

This is how most apps handle this type of list.  I suspect however, that since this breaks the flow of the current app, that it would be more of a 2.0.0 release target for this kind of change (if it were to be at all accepted).

**Comment by demoneaux** [comment]
This is currently how @phcoder does it in his fork, and seems like a good idea to me.

**Comment by schumaml** [comment]
cherry-pick (followed by a way to select where to) was definitely something I expected to find in a long press menu

**Comment by maks** [comment]
@bigdavedev agreed. I've had similar thoughts. 
I also am thinking that the app needs to make better use of fragments so tat for example when in landscape, on larger screens, it should be possible to have the view of a commits details side by side with the commit log listing. Though I'll raise a separate issue for that.

**Comment by bigdavedev** [comment]
@maks that would be nice if landscape made better use of screen real estate.  Especially since I am always on my 8" tablet :)

**Comment by maks** [comment]
Implemented as of af041326ce8ee25dbacc567aaddc679289552895
