### ISSUE TITLE
Inflater used after end

### ISSUE THREAD

**Issue by Lukas-Dresel** [sheimi/SGit#195]
While trying to clone this repository: https://github.com/uxmal/reko
It succeeds until it says updating references.

Then a short Toast appers that says something like "attempt to use inflate after end". 

It disappears very quickly, so i'm not sure. That however is a different issue since i assume that's the exception handling.

**Comment by maks** [comment]
Thank you for the report.
This is likely a duplicate of #169 which is due to insufficient memory to uncompress objects within packfiles.
