### ISSUE TITLE
Repositories stored on servers with self signed certificates is not supported.

### ISSUE THREAD

**Issue by diedthreetimes** [sheimi/SGit#2]
This is easily fixed by the git command 
$ git config http.sslVerify false

As far as I can tell there is no way to input this option.

Is there anyway to manually edit (or specify your own) .gitconfig file?

**Comment by maks** [comment]
Adding a root certificate for a self signed certificate is done at the OS level on Android. Instructions for how to do it for Android 4 onwards can be found here: http://stackoverflow.com/a/22040887/85472
