### ISSUE TITLE
Show author in commit log

### ISSUE THREAD

**Issue by schumaml** [sheimi/SGit#201]
The current commit log seems to show the committer, but not the aut5hor of a change. This is sometimes more interesting to know, especially if a project has many contributors who provide patches, but don't apply them to a code base.

**Comment by maks** [comment]
Agreed, though I'm not sure it should go into the current list item view. I think what's needed here is a detail view for commits too show this and the other fields from a commit, similar to what other git tools provide.

**Comment by maks** [comment]
This issue was moved to maks/MGit#31
