### ISSUE TITLE
Add file browser for setting local path 

### ISSUE THREAD

**Issue by skyducks** [sheimi/SGit#204]
When I clone repo, it's hard to set local path with text only.
How about add file browser for setting location?

**Comment by memeplex** [comment]
What will be the point of this when the app doesn't let you choose the root folder? That is the real issue IMO.

**Comment by skyducks** [comment]
@memeplex This is an usability issue. If the workspace is located in external sdcard or other directory, it is hard to copy the path. But in 'Import Repository' menu, it shows a file browser to add repository path. This is the same point of view.

**Comment by maks** [comment]
@memeplex these issues are related but not the same thing, lets please keep them seperate. I've opened a seperate issue for the default locat repo location: https://github.com/sheimi/SGit/issues/207

**Comment by maks** [comment]
on thinking about this some more and now that custom root dir for local repos has been implemented, I think this is not really needed, but being able to create repos in subdirs should be possible and the current limitation on that should be removed, for which I've created a new issue #226
