### ISSUE TITLE
failed resolution of: Lorg/ietf/jgss/oid

### ISSUE THREAD

**Issue by rclasen** [sheimi/SGit#205]
Hi,

when trying to connect to my git repo using ssh I keep getting this error message: "failed resolution of: Lorg/ietf/jgss/oid" (hand-copied - case may vary).

The SSH server is configured to support/offer kerberos/gss authentication - maybe this is related.

Is there a way to workaround this?

thanks,
 Rainer

**Comment by gergelypolonkai** [comment]
Same here, without Kerberos being involved. Using Android 6.0.1, maybe that matters.

**Comment by maks** [comment]
This issue was moved to maks/MGit#33
