### ISSUE TITLE
allow user to set default location for local repositories

### ISSUE THREAD

**Issue by maks** [sheimi/SGit#207]
currently the location is hardcoded to: `sdcard/Android/data/me.sheimi.sgit/files/`
its preferable to allow the user to instead set this via a preference in the app.

**Comment by flyisland** [comment]
+1, 
This would be more friendly for using other editors.

**Comment by jkufner** [comment]
I believe this is already implemented and selecting location outside internal storage is discussed in #233.

**Comment by maks** [comment]
Implemented as of 1.3.3
