### ISSUE TITLE
git-remote and git-revert missing

### ISSUE THREAD

**Issue by ARoiD** [sheimi/SGit#21]
Can't add remote gits or revert commits on the latest release?

http://git-scm.com/docs/git-remote
http://git-scm.com/docs/git-revert

**Comment by henrik242** [comment]
git-revert would have been great! It's the one feature I really miss on Android.

**Comment by henrik242** [comment]
Revert is covered in #173, by the way

**Comment by maks** [comment]
Even though this predates #173, since managing git remotes has now been implemented I'm closing this issues and will track adding git-revert in #173.
