### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by maks** [sheimi/SGit#224]
All new releases prior to general release are being made available to anyone interested in doing early testing via Google Play Beta releases.

Anyone who would like to try using a beta build can visit [this link](https://play.google.com/apps/testing/me.sheimi.sgit) to opt-in.

The latest release [v1.3.2](https://github.com/sheimi/SGit/releases/tag/v1.3.2) has just been uploaded to the Beta channel and should be available, any constructive feedback is most welcome.

**Comment by demoneaux** [comment]
:+1:!!

**Comment by memeplex** [comment]
I like this initiative. I'm curently testing the latest release. I see the milestone includes the "set root directory" feature, which is working fine for me. Nevertheless I'm a bit confused about the ultimate goal here: is it to let the user clone repos as subdirectories of the root directory or, eventually, to also let the user clone everywhere in the filesystem? Looking at the current milestone issues, I'm unable to figure out the answer.

**Comment by maks** [comment]
@memeplex Thank you for taking the time to test the beta release, please do file new issues for any problems that you may find.
With the new set root directory feature, the intention is to make the existing functionality (where all new local repos cloned from a remote) were stored in a location that was hard-coded in the app more flexible by allowing the user to override that location, which is now treated as just the initial default, instead of being hardcoded.
For me, this follows the common convention of git users to store all repos under a single root dir on the local filesystem. 
If you have any thoughts about how this might be improved, I'd be happy to discuss further either on gitter or if you raise a new issue for it here.
