### ISSUE TITLE
pull in all relevant commits from Forker fork

### ISSUE THREAD

**Issue by maks** [sheimi/SGit#231]
@phcoder has done great work on his fork. I'm going to pick up all relevant enhancements and bugfixes to integrate back into SGit. I say relevant, because some are bugfixes/enhancements that have already been done in SGit and some are no longer relevant, while others need some fixups.
This is all being done as a series of cherry-picks, some of which need extensive manual fixups and will land here as a single big merge.

**Comment by maks** [comment]
A list of the features being brought in:
* Multiline commit message amend
* Support for setting commit author
* Force pull and ability to choose remote for pull
* Force push and ability to choose remote for push (by Benjamin Tan)
* Rebase on non-local branch
* Show staged and unstaged diff

**Comment by goodevilgenius** [comment]
Any idea when these features will be implemented? Two of them (rebase on non-local and show staged diff) are features I use regularly, and I won't be able to switch back to SGit until they're done.

**Comment by maks** [comment]
@goodevilgenius I am getting towards the end of the process, you can see my progress so far [on this branch](https://github.com/maks/SGit/tree/phcoder-cherrypicks) I have it marked here (see milestone) for release in version 1.3.3 which per the process I've adopted is scheduled to go into the SGits Beta on Google Play on 24th Aug. Til now I've been leaving releases in Beta for about a week to get feedback and catch any showstopper bugs before pushing out to the production version on Play but given the large number of changes in this upcoming release I'll probably make that more like 2 weeks.
Hope that helps give you a better indication on when you'll be able to use the new features.

**Comment by goodevilgenius** [comment]
Sounds great. Glad to hear SGit is being so actively developed again.
