### ISSUE TITLE
Android N support

### ISSUE THREAD

**Issue by maks** [sheimi/SGit#232]
Via user review on Play is been reported that SGit is not working on Android 6.

**Comment by maks** [comment]
Turns out there is a *very* large number of reviews on Play from suers on 6.0 all reporting it does not work or crashes on start.

**Comment by PoisonRain** [comment]
I (the reviewer you responded to) am actually running android Marshmallow, not N. However, the same fix probably applies to both.

**Comment by Lrs121** [comment]
No problem on the Nexus 6 version of Android N Dev Preview 4.

**Comment by PoisonRain** [comment]
The issue appears to be fixed, as the app now works on my Nexus 6P.

**Comment by maks** [comment]
@PoisonRain sorry about that, I was answering a lot of reviews on Play and copy-pasted the wrong reply on a number,  for the reports about 6.0 I meant to instead just mention that the issue was fixed in the current release.

@Lrs121 Thanks for the report! I'll double check here too, but I suspect it was also fixed for N when fixed for M.

**Comment by maks** [comment]
I've tested current version myself running N on an x86 emulator image and it works wihtout issues so I'm closing this on the assumption that this was due to the same bug that caused SGit to crash on M as well that has since been fixed.
