### ISSUE TITLE
Basic stash support

### ISSUE THREAD

**Issue by memeplex** [sheimi/SGit#244]
When pulling there is the chance that local changes already happened. I can't see any reasonable way to deal with this situation besides dirty committing. Add at least the ability to "pull stashing": stash pull stash-pop.

**Comment by memeplex** [comment]
One more or less general and simple solution may be to detect the event "merging over uncommited changes" and show the user a dialog asking if he wants to abort or stash-merge-reapply local changes.

**Comment by memeplex** [comment]
Now I see the option "amend previous commit" does what I asked for, although it's a bit cumbersome to use: first commit, then pull, then fix conflicts, then stage (commit all won't work when merging), then commit ammending.

**Comment by maks** [comment]
I think stash functionality is very useful in its own right, I use it all the time with git, so I'm happy to get it added into SGit.

**Comment by maks** [comment]
This issue was moved to maks/MGit#37
