### ISSUE TITLE
Weird scrollbars(?) in commit diff view

### ISSUE THREAD

**Issue by memeplex** [sheimi/SGit#247]
See the grey bars at the right and bottom of each widget. Only when the contents are bigger than the window these bars don't appear. That is, if they were scrollbars they appear only in cases they're unnecessary while being hidden when they would have made sense.

![screenshot_2016-08-31-00-32-01](https://cloud.githubusercontent.com/assets/2845433/18115069/8d8c01ba-6f3c-11e6-85a0-b438c1c0e8fd.png)

**Comment by maks** [comment]
Hmm, that is strange, thanks for reporting this. I'll look into whats causing this.

**Comment by maks** [comment]
This issue was moved to maks/MGit#39
