### ISSUE TITLE
File browser does not display hidden directories

### ISSUE THREAD

**Issue by superjamie** [sheimi/SGit#250]
If a directory is "hidden" with a dot at the start of the name, that directory does not appear in the file listing

It's common for SSH keys to be in a directory called `.ssh` so this makes it impossible to add SSH private keys in such a directory.

**Comment by maks** [comment]
Duplicate of #243

**Comment by superjamie** [comment]
Ahh, I did look for duplicates but I missed that one, sorry. Thank you for the quick response!
