### ISSUE TITLE
Username is Ignored when Logging in via SSH

### ISSUE THREAD

**Issue by m1cm1c** [sheimi/SGit#253]
When I try to clone a repository via SSH and want to log in using username and password, I have to use

`ssh://username@server.com/path/to/repository`

If I use

`ssh://server.com/path/to/repository`

and enter the correct username and password, SGit tries to log in using the username `root` (which of course isn't the username I entered into the form).

I think SGit should try to log in using the username the user entered into the form.

**Comment by maks** [comment]
Thank you for taking the time to add the extra details in the issue here, its much easier than on Play store.
At first glance, I think SGit is not passing through the username field when using ssh, only for http.

**Comment by m1cm1c** [comment]
As a side note: I think before I wrote the bad review (which of course is deleted by now), I also tried `ssh://username@server.com/path/to/repository` a few times and it didn't work. However, I can't seem to be able to replicate it.

**Comment by maks** [comment]
This issue was moved to maks/MGit#41
