### ISSUE TITLE
Ignored files are shown in status page

### ISSUE THREAD

**Issue by m1cm1c** [sheimi/SGit#254]
In the gitignore in the root of my documents repo, I ignore all files ending with `~`. As you can see, on my computer it works (`s` does `git status`):
![](http://i.imgur.com/pljj52N.png)

SGit, on the other hand, shows me a lot of these files in its status page:
![](http://i.imgur.com/JuDQhnW.png)

(I censored some file names for privacy reasons.)

Because contents of the status page aren't scrollable, I can't even scroll down to see the changes I care about.

The gitignore file in the root of the repo is of course the same:
![](http://i.imgur.com/yEHl3Kr.png)

**Comment by maks** [comment]
Thanks for reporting this. Showing wrong information is not good at all. Ive marked this as high priority and will open a separate issue for the lack of scrolling.

**Comment by maks** [comment]
This issue was moved to maks/MGit#42
