### ISSUE TITLE
Commit messages does not show when done from GitKraken

### ISSUE THREAD

**Issue by briceparmentier** [sheimi/SGit#258]
Hi, 
I'm using since some weeks a new Git client on my pc which is called GitKraken. 
All the commits I've done with it correctly appear except the commit message. I can only view author and date, then I can correctly view the changes of each commit. 
Thanks !

**Comment by maks** [comment]
Thanks for reporting this issue. Would you have a publicly available repo where you are seeing this behaviour on the commit messages?

**Comment by briceparmentier** [comment]
Hem... Unfortunately this is a repo I personaly host so that it is not available right now...
But I can easily try to host a new repo within the next days and make some commits.
I will let you know when it is done.

**Comment by briceparmentier** [comment]
Here is the link to a repo on BitBucket where I made some a little commit : https://bitbucket.org/bridev/testrepo/commits/all

**Comment by briceparmentier** [comment]
Ok I have a new information. I didn't realize but GitKraken offers two fields to right a commit comment.
First one is the "summary", limited to 72 characters, and the second one is the "long" description.
It seems that only the second field is not recognized by SGit client for Android. If a do a commit from GitKraken by only typing in "summary", it works... Very strange...

**Comment by maks** [comment]
Ok, it sounds like GItKraken is trying to enforce the recommended convention for good commit messages, though the recommendation is for ~50 chars in the "summary" line, then blank line, then any extra information wrapped at ~72chars per line, ref: http://chris.beams.io/posts/git-commit/

You can see me following that convention as an example in this commit here: https://github.com/sheimi/SGit/commit/6ea23fc91504aed2548c369ab6d641ddba9eda03

SGit follows the above convention and only displays the summary line in the commit list, similar to what the canonical git does and other tools do, like here on github. If you then press on a commit in the list to see the details of the commit, you should then see the full commit message. I'm testing this at the moment on the current beta release from play store (v1.3.3) and it works, please update here if you still have issues.

**Comment by briceparmentier** [comment]
Thanks for this link about commit conventions. I didn't know about it before today !
So that it seems that the git core concatenate the two fields in a special way, and then clients are able to read only summary or the full description.
By the way, it seems that other systems can read the message even if the summary is not provided. Isn't it possible to display the "full description" if the summary is empty ?

**Comment by maks** [comment]
@briceparmentier I think you have rather misunderstood my previous comment.
There is nothing special and there are no "two fields" git commit messages are simply a block of plain text, its just a (recommended) convention that commit messages be split into first line, blank line, following lines. And tools such as SGit, Github, Bitbucket etc follow this convention and thus in commit listing UIs normally only display the first line of a commit message and then display the full commit message in a "detailed" commit UI view. And as I said this works in the current beta release of SGit also.

Displaying the first non-empty line of a commit message to work around commit messages that have not followed the recommended convention is not something I'd be keen to do at this time.
