### ISSUE TITLE
Feature request: markdown viewer

### ISSUE THREAD

**Issue by tonydiep** [sheimi/SGit#271]
I love this app. Thanks for making it. Below is a user story as a feature request.

STORY
As a user, I'd like to see Markdown files fully styled (instead of raw text) so that I don't have to open it in a Markdown editor.

POSSIBLE IMPLEMENTATIONS
- One possible implementation is [ForkHub's](https://github.com/jonan/ForkHub)

**Comment by maks** [comment]
Thanks for submitting such a well formatted feature request! 
And thanks also for the pointer to ForkHub - I hadn't come across it before, nice to see someone picked up and continued work on Githubs app.
I'll have a look at how ForkHub implements this and look at doing similar as this would be a very handy feature that I'd also like to use myself.

**Comment by maks** [comment]
This issue was moved to maks/MGit#46
