### ISSUE TITLE
cannot write to media storage

### ISSUE THREAD

**Issue by I-Dream-in-Code** [sheimi/SGit#272]
the app uses external storage on storage/emulated/0

my media storage (64 GB sdcard) is /storage/3937-3865 and I can't write to it.

I also cant root my tablet since it's pretty much impossible according to xda

**Comment by maks** [comment]
I'm not sure I understand the issue. Are you able to write to your "/storage/3937-3865" using other apps? If so you can the default location that SGit uses in SGit's settings.

**Comment by I-Dream-in-Code** [comment]
UPDATE: I learned about adoptable storage with 6.0.

so nevermind with this
