### ISSUE TITLE
Ability to update remotes

### ISSUE THREAD

**Issue by frankforte** [sheimi/SGit#285]
I may have missed it, but I did not see a way to edit a remote. Specifically the ability to change it's location, or it's user/password.

Maybe for authentication failures, showing a prompt that requests new credentials would help?

I am impressed with everything else so far.

**Comment by briceparmentier** [comment]
Hi, in any other GIT pc clients I can easily change the URL of the remote(s) I have for my repository.
Why could it be so hard to do here ?
I need this feature when I'm working at home or outside, and my box does not allow NAT loopback to work with my external dynamic DNS address to target the local device (not sure to be clear on the explanation of that point, don't hesitate to ask more)...

**Comment by frankforte** [comment]
I closed this thread after reading into it. This project was moved to MGit.

**Comment by briceparmentier** [comment]
Ok thanks for the information ! Is it this one https://github.com/maks/MGit ?

**Comment by maks** [comment]
@briceparmentier yes it is, I've created a new issue for this there: https://github.com/maks/MGit/issues/93
