### ISSUE TITLE
Dog

### ISSUE THREAD

**Issue by Ehrhardt1979** [sheimi/SGit#290]
Broke 

_Sent from my SM-G960U using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by tst2005** [comment]
https://github.com/sheimi/SGit#this-project-is-no-longer-being-maintained-further-development-on-this-app-is-now-being-done-in-the-mgit-project-please-submit-all-prs-and-issues-there

**Comment by Ehrhardt1979** [comment]
>

**Comment by Ehrhardt1979** [comment]
Bug

**Comment by maks** [comment]
https://github.com/sheimi/SGit#this-project-is-no-longer-being-maintained-further-development-on-this-app-is-now-being-done-in-the-mgit-project-please-submit-all-prs-and-issues-there
