### ISSUE TITLE
Unicode encoded files (with BOM)

### ISSUE THREAD

**Issue by keenonkites** [sheimi/SGit#43]
If there is a Unicode encoded file inside the repository using a BOM, the BOM seems to be displayed as a red dot as the first character of the file....
... the Encoding of the files themselves seems to be ok. Even editing seems to work.

You probably want to change that behaviour.

**Comment by d10** [comment]
We will be removing the editor in the next version of SGit, as the current editor (and others) have varied bugs which prevent proper editing of files. For now, you should use a specialized code editing app.
