### ISSUE TITLE
Bitbucket branch remotes not working

### ISSUE THREAD

**Issue by john-cheesman** [sheimi/SGit#54]
I have repositories on Github and Bitbucket, the Github ones work as expected getting branches and tags on clone. However, with my Bitbucket repos only the main branch works properly. All other branches are called 'refs/remot' and don't appear to have remotes set.

**Comment by evbo** [comment]
I am also unable to use "sgit" because it will not clone my remote branches off of bitbucket using https. As an example, the public repo greenkahuna/bootstyle has 2 branches - only master is cloned.

**Comment by john-cheesman** [comment]
@d10 I'm not using my phone for looking at code anymore but I believe it was HTTPS I was using.
