### ISSUE TITLE
clone a repository with private key

### ISSUE THREAD

**Issue by alex29ua** [sheimi/SGit#60]
I have a repository access which requires a private key instead of password (password-protected key is what I have).
I've added my key to SGit, but I don't see how to use it further. 
Is there such an option?

**Comment by waynespace** [comment]
I'm a fresh .so where to find my private key ?

**Comment by fmherschel** [comment]
I also miss the option or action to 'combine' a private key with a git remote repoitory. 

Now I have a git repository cloned but needed to temporary set a password I could type-in at the android and than closed the account again for pwd login.

I imported a private key (txt) file and can see it in the SGit App. My private key for this purpose does not have a password (which is not secure).

But still SGit asks for username/password.

How to "combine" the private key to the Git repository, so it gets used?

Is the a naming scheme for private keys?

**Comment by mlarcher** [comment]
The app looks great, but really lacks that passphrase feature on private keys. Are you planning on implementing it or is there some technical difficulties that represent too much of a challenge ?

**Comment by Lrs121** [comment]
These should help. This is how I clone projects and manage my keys. Sorry if this is long.

![screenshot_2015-09-04-16-59-23](https://cloud.githubusercontent.com/assets/3093776/9696614/0cfa16e4-5328-11e5-8a8a-6dd144b7e446.png)
![screenshot_2015-09-04-16-59-31](https://cloud.githubusercontent.com/assets/3093776/9696612/0cf6af0e-5328-11e5-82cd-d2b5e9a1b52b.png)
![screenshot_2015-09-04-17-04-44](https://cloud.githubusercontent.com/assets/3093776/9696613/0cf78226-5328-11e5-950c-effee039fd40.png)
![screenshot_2015-09-04-17-07-03](https://cloud.githubusercontent.com/assets/3093776/9696615/0cfc4824-5328-11e5-8981-50027886a62f.png)

**Comment by fmherschel** [comment]
Hmm I tried it that way, but it does not work for me. But I did not created the private/public key pair in putty. So which private/public key formats does SGit support? 
- Keys created with gpg?
- Keys created with ssh-keygen?
- Keys created with putty (f.e ppk)
- Others?

**Comment by Lrs121** [comment]
My key wasn't made with putty either, it was generated with Linux. however I use filezilla as a portable app and that doesn't support keys with a passphrase either. so filezilla stripped the pass phrase for me and that's what I use.

**Comment by endosynth** [comment]
+1 support for password protected private keys would be great.

note that my putty key without a password worked fine on an Android tablet, Samsung Tab4

**Comment by jgillich** [comment]
I had to enter the name of the key for username (`id_rsa` in my case), no idea if that's intended.

**Comment by maks** [comment]
This issue was moved to maks/MGit#66
