### ISSUE TITLE
Can't clone repository over SSH

### ISSUE THREAD

**Issue by ervinshiznit** [sheimi/SGit#65]
At 100% of updating references, it quits with the error "attempt to use Inflater after calling end."  https://android.googlesource.com/platform/libcore.git/+/android-4.2.2_r1/luni/src/main/java/java/util/zip/Inflater.java

**Comment by d10** [comment]
For GitHub SSH repos, you should clone via `git@github.com:TobiNet/Ticklist.git` instead of `ssh://git@github.com:TobiNet/Ticklist.git`. Not sure about the others. I've tried cloning BitBucket repos, they seem to work, although my repo is much smaller than 400 MB.

**Comment by TobiNet** [comment]
Ok, I get an Auth Fail now. I am using my correct github login. Same error using empty login..
I also get an Permission denied Error when I clone this via ssh on my PC.

**Comment by MrDanielSan** [comment]
I've had the same problem and found this issue in agit: https://github.com/rtyley/agit/issues/47

I looks like it's an jgit problem running on Android.

After adopting agit's HarmonyFixInflater.java class and using a patched jgit version ([1]) providing the InflaterFactory used in HarmonyFixInflater.java my previously broken clone does work.

Maybe the best place to fix this is in jgit, but I did not have time yet to see if there is an issue in jgit yet.

[1]: Using https://github.com/rtyley/jgit/commit/5ddb58a753b61ff4254d6840d062aea30f4b0e29 and https://github.com/rtyley/jgit/commit/4eb1ec20017efa7669714a39513fb48e85107bca on top of a vanilla jgit.

**Comment by maks** [comment]
This appears to be yet another instance of problems with cloning large repos due to memory constraints. I'm going to close this issue in favour of tracking all Inflater and memory issues around large repos in #169
