### ISSUE TITLE
Cannot import existing repository on USB drive

### ISSUE THREAD

**Issue by silvester747** [sheimi/SGit#67]
I have an ASUS TF700 which allows me to connect USB disks. I would like to be able to use repositories stored on the USB disk in SGit. Currently I can only import from internal storage.

My USB disks are mounted as /Removable/USBdisk#

There could be other devices that encounter similar problems for accessing external SD cards.

**Comment by phcoder** [comment]
What is the android version in question?

**Comment by maks** [comment]
Fixed as of v1.3.2
