### ISSUE TITLE
Bugs in SGit 1.2.4.4’s editor

### ISSUE THREAD

**Issue by hcksfch** [sheimi/SGit#75]
can't delete new line character and cause system crashed

**Comment by d10** [comment]
Yep, the editor is also unable to delete text sometimes. This is due to CodeMirror not supporting mobile devices well. There isn’t really anything we can do about that.

**Comment by d10** [comment]
We will be removing the editor in the next version of SGit, as the current editor (and others) have varied bugs which prevent proper editing of files. For now, you should use a specialized code editing app.
