### ISSUE TITLE
submodule command

### ISSUE THREAD

**Issue by Djfe** [sheimi/SGit#78]
there is no submodule command
-> you cannot do:
```git submodule foreach git pull origin master```

**Comment by d10** [comment]
Currently, we have no plans for adding support for this. I would appreciate it though if someone could send in a pull request.

**Comment by yvolk** [comment]
I read about submodules another time ( https://git-scm.com/book/en/v2/Git-Tools-Submodules ) and I decided that I better avoid them. So this feature is really not an important one...
