### ISSUE TITLE
[Feature Request] Better tablet support

### ISSUE THREAD

**Issue by impinball** [sheimi/SGit#83]
This is one of the greatest Git clients I've found for Android, but I seriously wish there was a version with tablets in mind. It is a fantastic tool for Android development, but the interface is made for phones.  I would be more inclined to scrap together a pull request if I had more than a beginner's clue in Android development (especially with UI).

**Comment by d10** [comment]
For now, we don't have any plans to work on this. I would gladly accept pull requests though.
