### ISSUE TITLE
Sleep while cloning

### ISSUE THREAD

**Issue by trenneman** [sheimi/SGit#91]
When I try to clone a large repository, _sgit_ falls asleep and aborts the cloning (without any decent error message, it sort of hangs). Probably using a wake lock should be sufficient. If you want, I can try to make a PR for that.

**Comment by maks** [comment]
Is there any evidence that SGit "falls asleep"?
I suspect cloning large repos is likely causing out of memory errors and thus is likely a duplicate of #169
