### ISSUE TITLE
Feature request: better staging support in UI

### ISSUE THREAD

**Issue by JimPanic** [sheimi/SGit#93]
I am currently trying to use SGit as main client on my TransformerPad TF701T and found some features to be lacking in terms of my usual workflow on Linux.
- show status of a file in the Files tab (staged, modified, up-to-date, untracked -- colors?)
- have an unstage button for already staged files on long press in Files tab (instead of "Add to stage")
- have the Status tab as interactive lists enabling one to add untracked files, stage/unstage, show diff, maybe even drag&drop the files between the list
- support for `git add --patch`

Apart from that, thanks for the great work so far. This is the first actually usable client I found on Android!

**Comment by maks** [comment]
This issue was moved to maks/MGit#63
