### ISSUE TITLE
Feature request: show status summary on commit

### ISSUE THREAD

**Issue by JimPanic** [sheimi/SGit#94]
It would be great to have a summary of the commit be listed upon pressing commit. Instead of a dialog, maybe even a tab next to Status could be used?

As additional feature, an optional diff output of the commit would be awesome.

**Comment by phcoder** [comment]
Should be fixed in https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit. Note: I made a fork only because my pull requests went unanswered. I'm welcoming any merge back into SGit.

**Comment by maks** [comment]
Implemented in af041326ce8ee25dbacc567aaddc679289552895
