### ISSUE TITLE
add support for orgmode in languages

### ISSUE THREAD

**Issue by zeltak** [sheimi/SGit#96]
Hi

great little app, just discoverd it.

i know this is a far fetched request but any chance at all to support orgmode syntax (similar to how markdown is supported):
http://orgmode.org/  (part of Emacs)

thx alot!

Z

**Comment by d10** [comment]
We will be removing the editor in the next version of SGit, as the current editor (and others) have varied bugs which prevent proper editing of files. For now, you should use a specialized code editing app.
